2014-11-26 03:16:38 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:16:56 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:17:21 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:17:41 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:17:44 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:18:07 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts/vieww
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:18:09 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts/view
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:18:11 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:18:12 Error: [MissingControllerException] Controller class PostsController could not be found.
Exception Attributes: array (
  'class' => 'PostsController',
  'plugin' => NULL,
)
Request URL: /niac/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2014-11-26 03:19:30 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /niac/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\niac\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-26 03:21:02 Error: [MissingActionException] Action PostsController::view() could not be found.
Exception Attributes: array (
  'controller' => 'PostsController',
  'action' => 'view',
)
Request URL: /niac/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Routing\Dispatcher.php(191): Controller->invokeAction(Object(CakeRequest))
#1 C:\xampp\htdocs\niac\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#2 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2014-11-26 03:22:49 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 11]
2014-11-26 03:22:49 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 11)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 11, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 11, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 03:23:52 Error: [MissingHelperException] Helper class ’Html’Helper could not be found.
Exception Attributes: array (
  'class' => '’Html’Helper',
  'plugin' => false,
)
Request URL: /niac/posts/view/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\View\View.php(886): HelperCollection->load('\x92Html\x92', Array)
#1 C:\xampp\htdocs\niac\lib\Cake\View\View.php(354): View->loadHelpers()
#2 C:\xampp\htdocs\niac\lib\Cake\Controller\Controller.php(1241): View->__construct(Object(PostsController))
#3 C:\xampp\htdocs\niac\lib\Cake\Controller\Controller.php(940): Controller->_getViewObject()
#4 C:\xampp\htdocs\niac\lib\Cake\Routing\Dispatcher.php(198): Controller->render()
#5 C:\xampp\htdocs\niac\lib\Cake\Routing\Dispatcher.php(165): Dispatcher->_invoke(Object(PostsController), Object(CakeRequest))
#6 C:\xampp\htdocs\niac\app\webroot\index.php(108): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#7 {main}
2014-11-26 18:57:40 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 33]
2014-11-26 18:57:40 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/view
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:57:51 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 33]
2014-11-26 18:57:51 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:57:57 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 33]
2014-11-26 18:57:57 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 33, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:58:35 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 32]
2014-11-26 18:58:35 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:58:37 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 32]
2014-11-26 18:58:37 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:58:53 Error: Fatal Error (4): syntax error, unexpected 'post’' (T_STRING) in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 32]
2014-11-26 18:58:53 Error: [FatalErrorException] syntax error, unexpected 'post’' (T_STRING)
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:59:17 Error: Fatal Error (4): syntax error, unexpected ';' in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 32]
2014-11-26 18:59:17 Error: [FatalErrorException] syntax error, unexpected ';'
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 32, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:59:39 Error: Fatal Error (4): syntax error, unexpected 'Post’' (T_STRING) in [C:\xampp\htdocs\niac\app\View\Posts\edit.ctp, line 9]
2014-11-26 18:59:39 Error: [FatalErrorException] syntax error, unexpected 'Post’' (T_STRING)
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 9, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 18:59:55 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 18:59:55 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:08:56 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:08:56 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:09:22 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:09:22 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:09:49 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:09:49 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:10:00 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:10:00 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/3
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:14:59 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:14:59 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/3
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:15:02 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:15:02 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/3
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:15:10 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:15:10 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/3
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:15:27 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:15:27 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:16:26 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:16:26 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:17:07 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:17:07 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:17:14 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:17:14 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:18:13 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:18:13 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:18:24 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:18:24 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:18:43 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 19:18:43 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/2
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:19:33 Error: Fatal Error (4): syntax error, unexpected '$post' (T_VARIABLE), expecting ')' in [C:\xampp\htdocs\niac\app\View\Posts\index.ctp, line 31]
2014-11-26 19:19:33 Error: [FatalErrorException] syntax error, unexpected '$post' (T_VARIABLE), expecting ')'
Request URL: /niac/posts/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 31)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 31, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 31, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:19:46 Error: Fatal Error (4): syntax error, unexpected 'Post’' (T_STRING) in [C:\xampp\htdocs\niac\app\View\Posts\add.ctp, line 8]
2014-11-26 19:19:46 Error: [FatalErrorException] syntax error, unexpected 'Post’' (T_STRING)
Request URL: /niac/posts/add
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 8, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:20:15 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 24]
2014-11-26 19:20:15 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/add
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:28:28 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 58]
2014-11-26 19:28:28 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/delete/4
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:28:40 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 24]
2014-11-26 19:28:40 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/add
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 19:29:00 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 58]
2014-11-26 19:29:00 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/delete/5
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 22:34:12 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 22:34:12 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 22:34:30 Error: Fatal Error (4): syntax error, unexpected ')' in [C:\xampp\htdocs\niac\app\View\Posts\index.ctp, line 34]
2014-11-26 22:34:30 Error: [FatalErrorException] syntax error, unexpected ')'
Request URL: /niac/
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 34)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 34, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 34, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-26 22:34:43 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-26 22:34:43 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-27 18:16:55 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 41]
2014-11-27 18:16:55 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/edit/1
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 41, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-27 18:17:02 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 58]
2014-11-27 18:17:02 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/delete/3
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 58, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2014-11-27 18:17:11 Error: Fatal Error (1): Call to a member function setFlash() on null in [C:\xampp\htdocs\niac\app\Controller\PostsController.php, line 24]
2014-11-27 18:17:11 Error: [FatalErrorException] Call to a member function setFlash() on null
Request URL: /niac/posts/add
Stack Trace:
#0 C:\xampp\htdocs\niac\lib\Cake\Error\ErrorHandler.php(203): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24, Array)
#2 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 24, Array)
#3 C:\xampp\htdocs\niac\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
